title: arifbudiman.web.id # The title of the blog
author: Arif Budiman # Your name
email: arifbudiman@outlook.com # your email shown in the footer
url: https://arifbudiman.web.id/ # this is your site's root address.
description: > # this means to ignore newlines until "show_excerpts:"
  A place to document anything worth remembering.
favicon: "./favicon.ico" # set the favicon of the site
show_excerpts: false # set to true to show excerpts on the homepage

# Moving date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
moving:
  avatar_url: "https://is3.cloudhost.id/arifbdarsono/arifbudimanwebid/assets/avatar-dalang-square.jpg" # avatar in about page
  about_you: Tech ðŸ’» and Automotive ðŸš˜ ðŸ›µ Enthusiast. # short description about you in about page
  date_format: "%b %d" # date format of posts in home page
  back_to: "Homepage" # In the post page, you have a back button above the title, you can custom the text by yourself.

  # generate social links in about page.
  social_links:
    twitter: arifbudiman
    # github: bukupedia
    rss: RSS
    # dribbble:
    # facebook: huangyz0918
    # flickr:
    # instagram: pedasnyamenyala
    # linkedin: yizheng-huang
    # pinterest:
    # youtube:
    # youtube_channel:
    # youtube_channel_name:
    # telegram:
    # googleplus:
    # microdotblog:
    # reddit:

    # Mastodon instances
    # mastodon:
    # - username:
    #   instance:
    # - username:
    #   instance:

# Build settings
remote_theme: huangyz0918/moving # note, please use huangyz0918/moving if you want to publish to Github Pages.

plugins:
  - jekyll-feed
  - jekyll-seo-tag
